# docker-compose.yml CORRIGIDO
services:
  api:
    build: .
    container_name: api_projeto
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./instance:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      # FLASK_RUN_HOST é definido pelo CMD do flask, não precisa mais aqui
      # mas o comando flask run --host=0.0.0.0 que é usado no CMD vai fazer o trabalho