services:
  api:
    build: .
    container_name: api_projeto
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./database.db:/instance/meubanco.db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0